Category component, weekly stats, service
MaxFangX/calendar-analytics pull request #103
Opened 2016-12-28 23:13 UTC by MaxFangX

- Create CategoryList component
- Create CategoryService
- No scope soup (: https://toddmotto.com/no-scope-soup-bind-to-controller-angularjs/
- Weekly ColorCategories

2016-12-28 23:15 UTC, MaxFangX commented
@cindytung no

2016-12-28 23:15 UTC, MaxFangX commented
<3

2016-12-29 08:06 UTC, jamesuejio requested changes
categories - cumulative preloader seems to be stuck. nevermind it works

2016-12-29 08:06 UTC, jamesuejio commented on cal/cal/static/js/app.js
> +  };
I thought we weren't going to be able to create categories. Can just remove this no? Might confuse people in the future.

2016-12-29 08:06 UTC, jamesuejio commented on cal/cal/static/js/services.js
> +  };
See above comment (we won't use create)

2016-12-29 08:06 UTC, jamesuejio commented on cal/api/views.py
> -            qs = qs.filter(end__lte=end)
Why did you delete this again?

2016-12-29 08:06 UTC, jamesuejio commented on cal/cal/static/js/services.js
> +          include: true
WHO GIVES A F*** ABOUT AN OXFORD COMMA https://www.youtube.com/watch?v=P_i1xk07o4g
Add a comma after include: true

2016-12-30 08:40 UTC, MaxFangX commented on cal/cal/static/js/app.js
> +  };
done

2016-12-30 08:41 UTC, MaxFangX commented on cal/cal/static/js/services.js
> +          include: true
done

2016-12-30 08:41 UTC, MaxFangX commented on cal/cal/static/js/services.js
> +  };
done

2016-12-30 08:42 UTC, MaxFangX commented on cal/api/views.py
> -            qs = qs.filter(end__lte=end)
This breaks it - a `Tag` doesn't have a start parameter so it causes a 500 error

2016-12-30 08:42 UTC, jalagar commented on cal/api/views.py
> -            qs = qs.filter(end__lte=end)
Okay

2016-12-30 08:51 UTC, jamesuejio approved these changes

2016-12-30 08:51 UTC, merged