Add preloader to calendar and show 404
MaxFangX/calendar-analytics pull request #147
Opened 2017-01-23 01:56 UTC by tiffanyqi

- add preloader to calendar
- 404 page, of lake victoria basically
- to see the 404, set debug to False in Dev

2017-01-23 09:11 UTC, jamesuejio requested changes
404 doesn't seem to work for me. http://localhost:8000/fdsfsda gives regular Page Not Found error. Could be bower stuff, so maybe merge master in and lmk again :)

2017-01-23 09:11 UTC, jalagar commented on cal/cal/static/js/components/calendar.js
> +
Whats with the two extra lines?

2017-01-23 09:18 UTC, jamesuejio requested changes

2017-01-23 09:18 UTC, jalagar commented on cal/cal/static/js/components/calendar.js
> +   $scope.loading = function(isLoading, view){
I thought we didn't want to use $scope? @MaxFangX ?

2017-01-23 23:45 UTC, MaxFangX commented on cal/cal/views.py
> +    response = render_to_response('404.html', {},
`render_to_response` [is "likely to be deprecated in the future"](https://docs.djangoproject.com/en/1.10/topics/http/shortcuts/#render-to-response)

2017-01-23 23:46 UTC, MaxFangX commented on cal/cal/static/js/components/calendar.js
> +   $scope.loading = function(isLoading, view){
Correct! Bind to `this`

2017-01-23 23:46 UTC, MaxFangX commented on cal/cal/templates/404.html
> +    <h2>This link doesn't exist! :( Here's a beautiful waterfront. When you're ready go to back, click <a href="/">here to return to your dashboard</a></h2>.
Our html is 2 spaces, not 4

2017-01-23 23:47 UTC, MaxFangX reviewed
Small fixes, but otherwise LGTM

2017-02-05 07:53 UTC, tiffanyqi reviewed
Looks like some comments disappeared after my push: essentially this is what it was: 
- removed two line breaks in calendar.js
- changed `$scope.loading` to `this.loading` with a `bind(this)`
- changed from 4 spaces to 2 spaces in 404.html

2017-02-05 07:53 UTC, tiffanyqi commented on cal/cal/static/js/components/calendar.js
> +
must have been an accident; thanks for checking! fixing

2017-02-05 07:53 UTC, tiffanyqi commented on cal/cal/templates/404.html
> +    <h2>This link doesn't exist! :( Here's a beautiful waterfront. When you're ready go to back, click <a href="/">here to return to your dashboard</a></h2>.
cool, fixing

2017-02-05 07:53 UTC, tiffanyqi commented on cal/cal/static/js/components/calendar.js
> +   $scope.loading = function(isLoading, view){
what about like `$scope.eventRender` right above it? or are we going to refactor those things later? changing this anyway, just wondering

2017-02-05 07:56 UTC, tiffanyqi commented on cal/cal/views.py
> +    response = render_to_response('404.html', {},
@MaxFangX noooo, what should i do instead ;(

2017-02-05 07:57 UTC, tiffanyqi commented
@jalagar 404 does it work! If you go to settings.py and change your current env to `Debug = False`, you'll see it

2017-02-20 00:27 UTC, tiffanyqi commented
@jalagar implemented @MaxFangX 's changes

2017-02-20 02:15 UTC, jamesuejio approved these changes

2017-02-20 06:03 UTC, merged