Default event colors use calendar color, move all day events to top of UI
MaxFangX/calendar-analytics pull request #57
Opened 2016-10-24 03:29 UTC by MaxFangX

2016-10-24 18:47 UTC, tiffanyqi requested changes

2016-10-24 18:47 UTC, tiffanyqi commented on cal/cal/migrations/0043_gcalendar_color_index.py
> +            field=models.CharField(default='10', max_length=10, choices=[(b'1', b'#a4bdfc'), (b'2', b'#7ae7bf'), (b'3', b'#dbadff'), (b'4', b'#ff887c'), (b'5', b'#fbd75b'), (b'6', b'#ffb878'), (b'7',
What are these? Are these the google calendar colors, and where are you using this in the code?

2016-10-24 18:47 UTC, tiffanyqi commented on cal/cal/models.py
> +            gcal.color_index = item.get('colorId', '1')
what's the '1'? is that the default color for the calendar? if so, why is it applied to all?

2016-10-24 18:47 UTC, tiffanyqi commented on cal/cal/static/js/app.js
> +                          allDay: gevent.all_day_event,
+1 tested, this works so well

2016-10-24 18:48 UTC, tiffanyqi approved these changes

2016-10-24 18:49 UTC, tiffanyqi commented
Oops, made a mistake. Meant to "comment" but not review, but then approved my changes (oops). Could you address these comments please? Thanks!

2016-10-24 19:57 UTC, MaxFangX commented on cal/cal/migrations/0043_gcalendar_color_index.py
> +            field=models.CharField(default='10', max_length=10, choices=[(b'1', b'#a4bdfc'), (b'2', b'#7ae7bf'), (b'3', b'#dbadff'), (b'4', b'#ff887c'), (b'5', b'#fbd75b'), (b'6', b'#ffb878'), (b'7',
This is the generated migrations code from Django. It adds a new field color_index with all the possible options of colors as defined in constants.py. There are list comprehensions in the GCalendar class that you may look at in the shell

2016-10-24 19:59 UTC, MaxFangX commented on cal/cal/migrations/0043_gcalendar_color_index.py
> +            field=models.CharField(default='10', max_length=10, choices=[(b'1', b'#a4bdfc'), (b'2', b'#7ae7bf'), (b'3', b'#dbadff'), (b'4', b'#ff887c'), (b'5', b'#fbd75b'), (b'6', b'#ffb878'), (b'7',
It is used in the code in GEvent.color when it refers to self.calrndar.color!

2016-10-24 20:32 UTC, MaxFangX commented on cal/cal/models.py
> +            gcal.color_index = item.get('colorId', '1')
get avoids key errors by returning a default value if a specified key is not found. '1' is the default color, yes, and will be set as such when a colorId key doesn't exist

2016-10-24 20:49 UTC, tiffanyqi commented
@MaxFangX thanks! LGTM. Waiting on @jalagar, if he'd like to take a look

2016-10-25 07:59 UTC, jalagar commented
+2

2016-10-25 08:00 UTC, merged