Calendarclick
MaxFangX/calendar-analytics pull request #63
Opened 2016-10-27 22:35 UTC by jalagar

Add feature to click on events to open up description.

2016-10-27 22:49 UTC, jalagar commented
#49

2016-10-27 22:52 UTC, jalagar commented
#54

2016-10-28 05:07 UTC, MaxFangX requested changes

2016-10-28 05:07 UTC, MaxFangX commented on cal/cal/static/css/calendaranalytics.css
> +
Make sure you use sass. Modify `calendaranalytics.scss` and compile the css changes (this css code is generated)

2016-10-28 05:07 UTC, MaxFangX commented on cal/cal/static/css/calendaranalytics.css
> +}
As I told Tiffany earlier, we use namespaced classes: [link to conversation](https://github.com/MaxFangX/calendar-analytics/pull/61/files/82d6ad8a5a9ee7cdc9b6e89f49c4ee6eed1bfc0d#r84846777). Could you change this to `.cal-section-info`? Let me know if you disagree

2016-10-28 05:07 UTC, MaxFangX commented on cal/cal/static/css/calendaranalytics.css
> +.fc-content {
Where is the `fc-content` class used? I can't find it in the PR

2016-10-28 05:07 UTC, MaxFangX commented on cal/cal/static/js/app.js
> +        location = '<i>' + event.location + '</i></br>'
Hmm, shouldn't it be `<br>` instead of `</br>`? I might be wrong

2016-10-28 05:07 UTC, MaxFangX commented on cal/cal/templates/base.html
> +      <link rel="stylesheet" href="http://cdn.jsdelivr.net/qtip2/3.0.3/jquery.qtip.min.css">
This should go anywhere after calendaranalytics.css, since we first want our base styling (bootstrap), then our custom styling (calendaranalytics.css), and then lastly our library stylings (this)

2016-10-28 05:07 UTC, MaxFangX commented on cal/cal/templates/base.html
> +      <script type="text/javascript" src="http://cdn.jsdelivr.net/qtip2/3.0.3/jquery.qtip.min.js"></script>
Could you put this line with all of the other javascript libraries (in the head)? Wherever you think it makes the most sense.

2016-10-28 05:07 UTC, MaxFangX commented on cal/cal/templates/home_logged_in.html
> -            <tr ng-repeat="tag in tags">
Not sure how this happened but you somehow deleted all the functionality that Tiffany had built [here](https://github.com/MaxFangX/calendar-analytics/pull/43). Could you add it back and then reimplement these changes? This looks like the offending commit: [https://github.com/MaxFangX/calendar-analytics/pull/63/commits/91bb9f98fdd447310629f58952950ecb538b205d](https://github.com/MaxFangX/calendar-analytics/pull/63/commits/91bb9f98fdd447310629f58952950ecb538b205d)

2016-10-28 05:15 UTC, MaxFangX commented
Btw, I don't think the issues will automatically close unless they are referred to in the original comment. Happened to me and Tiffany before

2016-10-29 01:24 UTC, jamesuejio commented on cal/cal/static/css/calendaranalytics.css
> +}
Changed

2016-10-29 01:27 UTC, jamesuejio commented on cal/cal/static/css/calendaranalytics.css
> +.fc-content {
This is for mouse hover so when you hover over the name of the event, the mouse cursor turns to pointer. fc-content located in the FullCalendar.js and html files and stuff.

2016-10-29 01:28 UTC, jalagar commented on cal/cal/static/css/calendaranalytics.css
> +
I'm not sure what you mean by this, I just copy and pasted the code in calendaranalystics.scss

2016-10-29 01:29 UTC, jalagar commented on cal/cal/static/js/app.js
> +        location = '<i>' + event.location + '</i></br>'
Sure, either work, I'll change it to <br> to delete a character.

2016-10-29 01:31 UTC, jalagar commented on cal/cal/templates/base.html
> +      <link rel="stylesheet" href="http://cdn.jsdelivr.net/qtip2/3.0.3/jquery.qtip.min.css">
I'll put it last.

2016-10-29 01:31 UTC, jalagar commented on cal/cal/templates/base.html
> +      <script type="text/javascript" src="http://cdn.jsdelivr.net/qtip2/3.0.3/jquery.qtip.min.js"></script>
Ok

2016-10-29 01:41 UTC, jamesuejio commented on cal/cal/static/css/calendaranalytics.scss
> +/*# sourceMappingURL=calendaranalytics.css.map */
Not sure what happened here.

2016-10-29 01:42 UTC, jalagar commented on cal/cal/templates/home_logged_in.html
> +            <tr ng-repeat="tag in tags | orderBy:orderByField:reverseSort">
I also don't know what happened here, how did these get pushed?

2016-10-29 01:43 UTC, jalagar commented on cal/cal/templates/home_logged_in.html
> +            <tr ng-repeat="tag in tags | orderBy:orderByField:reverseSort">
Should I revert the red or...?

2016-10-29 06:43 UTC, MaxFangX commented on cal/cal/static/css/calendaranalytics.css
> +
That's the right idea. See the sass command [here](https://github.com/MaxFangX/calendar-analytics/blob/master/cal/README.md)? After you've installed sass, run it just like you would a "runserver" command. Then change any of the .scss files and it will automatically compile the .css files.

2016-10-29 06:44 UTC, MaxFangX commented on cal/cal/static/css/calendaranalytics.css
> +.fc-content {
Ahh, makes sense. May I suggest you write in a comment so anyone in the future knows why that's there?

2016-10-29 06:46 UTC, MaxFangX commented on cal/cal/static/css/calendaranalytics.scss
> +/*# sourceMappingURL=calendaranalytics.css.map */
Was this code generated? If so, I wouldn't worry about it.

2016-10-29 06:46 UTC, MaxFangX commented on cal/cal/templates/home_logged_in.html
> +            <tr ng-repeat="tag in tags | orderBy:orderByField:reverseSort">
lol

2016-10-29 06:47 UTC, MaxFangX commented on cal/cal/templates/home_logged_in.html
> +            <tr ng-repeat="tag in tags | orderBy:orderByField:reverseSort">
Merge from master and it should go away. Your branch is currently out of date so Github thinks you want to undo Tiffany's commits

2016-10-29 06:49 UTC, MaxFangX commented on cal/cal/static/css/calendaranalytics.scss
> +/*# sourceMappingURL=calendaranalytics.css.map */
Oh, it might have been from Tiffany. Try merging from master and see if it goes away

2016-10-29 06:52 UTC, MaxFangX commented on cal/cal/static/css/calendaranalytics.css
> +
Basically, you should never have to modify .css files. Instead, you can take advantage of the superior syntax of sass, including nested selectors and variables B)

2016-10-29 19:11 UTC, jalagar commented on cal/cal/static/css/calendaranalytics.css
> +
Got it

2016-10-29 21:26 UTC, MaxFangX approved these changes

2016-10-29 23:20 UTC, merged

2016-10-30 00:08 UTC, MaxFangX commented
WOOOO

2016-10-30 00:09 UTC, MaxFangX commented
Hmm, the issue didn't close. Maybe you are supposed to write "Fixes #49" (that's what works for me, anyway)